### ISSUE TITLE
Using Postgres

### ISSUE THREAD

**Issue by brydavis** [salimhamed/dashboard#1]
1. Be sure to install [libpq-dev](http://stackoverflow.com/questions/18864112/installing-the-postgresql-gem-with-gem-pq-fails-with-error-failed-to-build-ge) via `apt-get install libpq-dev`
2. `apt-get install python-dev`
3. `pip install psycopg2`
4. Add the driver string `postgresql+psycopg2://user:password@host:port/dbname` to the file `config.py`

**Comment by ghost** [comment]
thanks
